name: Generate Code Coverage
on: [pull_request]
  
jobs:
  cover-base:
    name: Generate Base Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.2'

      - name: Generate report
        run: |
          go test -coverprofile base-coverage.tmp ./cmd/... ./pkg/...
          cat base-coverage.tmp | grep -v "mock_" > base-coverage.out

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: base-coverage
          path: base-coverage.out

  cover-pr:
    name: Generate PR Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.2'

      - name: Generate report
        run: |
          go test -coverprofile pr-coverage.tmp ./cmd/... ./pkg/...
          cat pr-coverage.tmp | grep -v "mock_" > pr-coverage.out

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: pr-coverage
          path: pr-coverage.out
